name: TradeBlocks CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv with Python 3.11
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Sync dependencies
        run: uv sync --group dev --frozen

      - name: Code formatting check (advisory)
        run: |
          uv run --group dev black --check app/ --diff \
            || echo "⚠️ Code formatting issues found (non-blocking)"

      - name: Lint with ruff (advisory)
        run: |
          uv run --group dev ruff check app/ \
            || echo "⚠️ Linting issues found (non-blocking)"

      - name: Test import structure
        run: |
          uv run --group dev python -c "from app.main import app; print('✅ App imports successfully')"

      - name: Run tests
        run: |
          if [ -d "tests" ] && [ "$(ls -A tests)" ]; then
            uv run --group dev pytest tests/ -v --cov=app --cov-report=term-missing
          else
            echo "ℹ️ No tests found, skipping test execution"
          fi

  render-ready:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Ensure Render build assets are present
        run: |
          test -f uv.lock || (echo "❌ uv.lock missing" && exit 1)
          test -f buildfiles.sh || (echo "❌ buildfiles.sh missing" && exit 1)
          test -f vercel.json && echo "ℹ️ vercel.json found (optional)"

      - name: Verify build script
        run: |
          chmod +x buildfiles.sh
          ./buildfiles.sh

      - name: Confirm start script exists
        run: |
          test -f scripts/start-dev.sh || (echo "❌ scripts/start-dev.sh missing" && exit 1)
          echo "✅ Render start assets verified"
